# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import core_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='files.proto',
  package='rsctrl.files',
  serialized_pb='\n\x0b\x66iles.proto\x12\x0crsctrl.files\x1a\ncore.proto\"\x7f\n\x0c\x46ileTransfer\x12\x1f\n\x04\x66ile\x18\x01 \x02(\x0b\x32\x11.rsctrl.core.File\x12*\n\tdirection\x18\x02 \x02(\x0e\x32\x17.rsctrl.files.Direction\x12\x10\n\x08\x66raction\x18\x03 \x02(\x02\x12\x10\n\x08rate_kBs\x18\x04 \x02(\x02\"A\n\x13RequestTransferList\x12*\n\tdirection\x18\x01 \x02(\x0e\x32\x17.rsctrl.files.Direction\"j\n\x14ResponseTransferList\x12#\n\x06status\x18\x01 \x02(\x0b\x32\x13.rsctrl.core.Status\x12-\n\ttransfers\x18\x02 \x03(\x0b\x32\x1a.rsctrl.files.FileTransfer\"\x84\x02\n\x16RequestControlDownload\x12\x1f\n\x04\x66ile\x18\x01 \x02(\x0b\x32\x11.rsctrl.core.File\x12;\n\x06\x61\x63tion\x18\x02 \x02(\x0e\x32+.rsctrl.files.RequestControlDownload.Action\"\x8b\x01\n\x06\x41\x63tion\x12\x10\n\x0c\x41\x43TION_START\x10\x01\x12\x13\n\x0f\x41\x43TION_CONTINUE\x10\x02\x12\x0f\n\x0b\x41\x43TION_WAIT\x10\x03\x12\x10\n\x0c\x41\x43TION_PAUSE\x10\x04\x12\x12\n\x0e\x41\x43TION_RESTART\x10\x05\x12\x10\n\x0c\x41\x43TION_CHECK\x10\x06\x12\x11\n\rACTION_CANCEL\x10\x07\">\n\x17ResponseControlDownload\x12#\n\x06status\x18\x01 \x02(\x0b\x32\x13.rsctrl.core.Status*P\n\rRequestMsgIds\x12\x1d\n\x19MsgId_RequestTransferList\x10\x01\x12 \n\x1cMsgId_RequestControlDownload\x10\x02*S\n\x0eResponseMsgIds\x12\x1e\n\x1aMsgId_ResponseTransferList\x10\x01\x12!\n\x1dMsgId_ResponseControlDownload\x10\x02*9\n\tDirection\x12\x14\n\x10\x44IRECTION_UPLOAD\x10\x01\x12\x16\n\x12\x44IRECTION_DOWNLOAD\x10\x02')

_REQUESTMSGIDS = descriptor.EnumDescriptor(
  name='RequestMsgIds',
  full_name='rsctrl.files.RequestMsgIds',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MsgId_RequestTransferList', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MsgId_RequestControlDownload', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=672,
  serialized_end=752,
)


_RESPONSEMSGIDS = descriptor.EnumDescriptor(
  name='ResponseMsgIds',
  full_name='rsctrl.files.ResponseMsgIds',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MsgId_ResponseTransferList', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MsgId_ResponseControlDownload', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=754,
  serialized_end=837,
)


_DIRECTION = descriptor.EnumDescriptor(
  name='Direction',
  full_name='rsctrl.files.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='DIRECTION_UPLOAD', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DIRECTION_DOWNLOAD', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=839,
  serialized_end=896,
)


MsgId_RequestTransferList = 1
MsgId_RequestControlDownload = 2
MsgId_ResponseTransferList = 1
MsgId_ResponseControlDownload = 2
DIRECTION_UPLOAD = 1
DIRECTION_DOWNLOAD = 2


_REQUESTCONTROLDOWNLOAD_ACTION = descriptor.EnumDescriptor(
  name='Action',
  full_name='rsctrl.files.RequestControlDownload.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ACTION_START', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTION_CONTINUE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTION_WAIT', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTION_PAUSE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTION_RESTART', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTION_CHECK', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTION_CANCEL', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=467,
  serialized_end=606,
)


_FILETRANSFER = descriptor.Descriptor(
  name='FileTransfer',
  full_name='rsctrl.files.FileTransfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='file', full_name='rsctrl.files.FileTransfer.file', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='direction', full_name='rsctrl.files.FileTransfer.direction', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fraction', full_name='rsctrl.files.FileTransfer.fraction', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rate_kBs', full_name='rsctrl.files.FileTransfer.rate_kBs', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=168,
)


_REQUESTTRANSFERLIST = descriptor.Descriptor(
  name='RequestTransferList',
  full_name='rsctrl.files.RequestTransferList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='direction', full_name='rsctrl.files.RequestTransferList.direction', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=170,
  serialized_end=235,
)


_RESPONSETRANSFERLIST = descriptor.Descriptor(
  name='ResponseTransferList',
  full_name='rsctrl.files.ResponseTransferList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='rsctrl.files.ResponseTransferList.status', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transfers', full_name='rsctrl.files.ResponseTransferList.transfers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=237,
  serialized_end=343,
)


_REQUESTCONTROLDOWNLOAD = descriptor.Descriptor(
  name='RequestControlDownload',
  full_name='rsctrl.files.RequestControlDownload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='file', full_name='rsctrl.files.RequestControlDownload.file', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='action', full_name='rsctrl.files.RequestControlDownload.action', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTCONTROLDOWNLOAD_ACTION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=346,
  serialized_end=606,
)


_RESPONSECONTROLDOWNLOAD = descriptor.Descriptor(
  name='ResponseControlDownload',
  full_name='rsctrl.files.ResponseControlDownload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='rsctrl.files.ResponseControlDownload.status', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=608,
  serialized_end=670,
)

_FILETRANSFER.fields_by_name['file'].message_type = core_pb2._FILE
_FILETRANSFER.fields_by_name['direction'].enum_type = _DIRECTION
_REQUESTTRANSFERLIST.fields_by_name['direction'].enum_type = _DIRECTION
_RESPONSETRANSFERLIST.fields_by_name['status'].message_type = core_pb2._STATUS
_RESPONSETRANSFERLIST.fields_by_name['transfers'].message_type = _FILETRANSFER
_REQUESTCONTROLDOWNLOAD.fields_by_name['file'].message_type = core_pb2._FILE
_REQUESTCONTROLDOWNLOAD.fields_by_name['action'].enum_type = _REQUESTCONTROLDOWNLOAD_ACTION
_REQUESTCONTROLDOWNLOAD_ACTION.containing_type = _REQUESTCONTROLDOWNLOAD;
_RESPONSECONTROLDOWNLOAD.fields_by_name['status'].message_type = core_pb2._STATUS
DESCRIPTOR.message_types_by_name['FileTransfer'] = _FILETRANSFER
DESCRIPTOR.message_types_by_name['RequestTransferList'] = _REQUESTTRANSFERLIST
DESCRIPTOR.message_types_by_name['ResponseTransferList'] = _RESPONSETRANSFERLIST
DESCRIPTOR.message_types_by_name['RequestControlDownload'] = _REQUESTCONTROLDOWNLOAD
DESCRIPTOR.message_types_by_name['ResponseControlDownload'] = _RESPONSECONTROLDOWNLOAD

class FileTransfer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILETRANSFER
  
  # @@protoc_insertion_point(class_scope:rsctrl.files.FileTransfer)

class RequestTransferList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTTRANSFERLIST
  
  # @@protoc_insertion_point(class_scope:rsctrl.files.RequestTransferList)

class ResponseTransferList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSETRANSFERLIST
  
  # @@protoc_insertion_point(class_scope:rsctrl.files.ResponseTransferList)

class RequestControlDownload(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTCONTROLDOWNLOAD
  
  # @@protoc_insertion_point(class_scope:rsctrl.files.RequestControlDownload)

class ResponseControlDownload(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSECONTROLDOWNLOAD
  
  # @@protoc_insertion_point(class_scope:rsctrl.files.ResponseControlDownload)

# @@protoc_insertion_point(module_scope)
