# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import core_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='search.proto',
  package='rsctrl.search',
  serialized_pb='\n\x0csearch.proto\x12\rrsctrl.search\x1a\ncore.proto\"\x8c\x01\n\tSearchHit\x12\x1f\n\x04\x66ile\x18\x01 \x02(\x0b\x32\x11.rsctrl.core.File\x12\x0b\n\x03loc\x18\x02 \x02(\r\x12\x0f\n\x07no_hits\x18\x03 \x02(\r\x12\x11\n\talt_names\x18\x04 \x03(\t\"-\n\x07LocFlag\x12\t\n\x05LOCAL\x10\x01\x12\n\n\x06\x46RIEND\x10\x02\x12\x0b\n\x07NETWORK\x10\x04\"F\n\tSearchSet\x12\x11\n\tsearch_id\x18\x01 \x02(\r\x12&\n\x04hits\x18\x02 \x03(\x0b\x32\x18.rsctrl.search.SearchHit\"#\n\x12RequestBasicSearch\x12\r\n\x05terms\x18\x01 \x03(\t\"!\n\x10RequestAdvSearch\x12\r\n\x05terms\x18\x01 \x03(\t\"K\n\x11ResponseSearchIds\x12#\n\x06status\x18\x01 \x02(\x0b\x32\x13.rsctrl.core.Status\x12\x11\n\tsearch_id\x18\x02 \x03(\r\"\'\n\x12RequestCloseSearch\x12\x11\n\tsearch_id\x18\x01 \x02(\r\"\x15\n\x13RequestListSearches\"@\n\x14RequestSearchResults\x12\x14\n\x0cresult_limit\x18\x01 \x01(\r\x12\x12\n\nsearch_ids\x18\x02 \x03(\r\"h\n\x15ResponseSearchResults\x12#\n\x06status\x18\x01 \x02(\x0b\x32\x13.rsctrl.core.Status\x12*\n\x08searches\x18\x02 \x03(\x0b\x32\x18.rsctrl.search.SearchSet*\x8a\x01\n\rRequestMsgIds\x12\x1c\n\x18MsgId_RequestBasicSearch\x10\x01\x12\x1c\n\x18MsgId_RequestCloseSearch\x10\x03\x12\x1d\n\x19MsgId_RequestListSearches\x10\x04\x12\x1e\n\x1aMsgId_RequestSearchResults\x10\x05*N\n\x0eResponseMsgIds\x12\x1b\n\x17MsgId_ResponseSearchIds\x10\x01\x12\x1f\n\x1bMsgId_ResponseSearchResults\x10\x05')

_REQUESTMSGIDS = descriptor.EnumDescriptor(
  name='RequestMsgIds',
  full_name='rsctrl.search.RequestMsgIds',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MsgId_RequestBasicSearch', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MsgId_RequestCloseSearch', index=1, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MsgId_RequestListSearches', index=2, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MsgId_RequestSearchResults', index=3, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=644,
  serialized_end=782,
)


_RESPONSEMSGIDS = descriptor.EnumDescriptor(
  name='ResponseMsgIds',
  full_name='rsctrl.search.ResponseMsgIds',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MsgId_ResponseSearchIds', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MsgId_ResponseSearchResults', index=1, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=784,
  serialized_end=862,
)


MsgId_RequestBasicSearch = 1
MsgId_RequestCloseSearch = 3
MsgId_RequestListSearches = 4
MsgId_RequestSearchResults = 5
MsgId_ResponseSearchIds = 1
MsgId_ResponseSearchResults = 5


_SEARCHHIT_LOCFLAG = descriptor.EnumDescriptor(
  name='LocFlag',
  full_name='rsctrl.search.SearchHit.LocFlag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='LOCAL', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FRIEND', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NETWORK', index=2, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=139,
  serialized_end=184,
)


_SEARCHHIT = descriptor.Descriptor(
  name='SearchHit',
  full_name='rsctrl.search.SearchHit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='file', full_name='rsctrl.search.SearchHit.file', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='loc', full_name='rsctrl.search.SearchHit.loc', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='no_hits', full_name='rsctrl.search.SearchHit.no_hits', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='alt_names', full_name='rsctrl.search.SearchHit.alt_names', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SEARCHHIT_LOCFLAG,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=184,
)


_SEARCHSET = descriptor.Descriptor(
  name='SearchSet',
  full_name='rsctrl.search.SearchSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='search_id', full_name='rsctrl.search.SearchSet.search_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hits', full_name='rsctrl.search.SearchSet.hits', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=186,
  serialized_end=256,
)


_REQUESTBASICSEARCH = descriptor.Descriptor(
  name='RequestBasicSearch',
  full_name='rsctrl.search.RequestBasicSearch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='terms', full_name='rsctrl.search.RequestBasicSearch.terms', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=258,
  serialized_end=293,
)


_REQUESTADVSEARCH = descriptor.Descriptor(
  name='RequestAdvSearch',
  full_name='rsctrl.search.RequestAdvSearch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='terms', full_name='rsctrl.search.RequestAdvSearch.terms', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=295,
  serialized_end=328,
)


_RESPONSESEARCHIDS = descriptor.Descriptor(
  name='ResponseSearchIds',
  full_name='rsctrl.search.ResponseSearchIds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='rsctrl.search.ResponseSearchIds.status', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='search_id', full_name='rsctrl.search.ResponseSearchIds.search_id', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=330,
  serialized_end=405,
)


_REQUESTCLOSESEARCH = descriptor.Descriptor(
  name='RequestCloseSearch',
  full_name='rsctrl.search.RequestCloseSearch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='search_id', full_name='rsctrl.search.RequestCloseSearch.search_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=407,
  serialized_end=446,
)


_REQUESTLISTSEARCHES = descriptor.Descriptor(
  name='RequestListSearches',
  full_name='rsctrl.search.RequestListSearches',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=448,
  serialized_end=469,
)


_REQUESTSEARCHRESULTS = descriptor.Descriptor(
  name='RequestSearchResults',
  full_name='rsctrl.search.RequestSearchResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result_limit', full_name='rsctrl.search.RequestSearchResults.result_limit', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='search_ids', full_name='rsctrl.search.RequestSearchResults.search_ids', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=471,
  serialized_end=535,
)


_RESPONSESEARCHRESULTS = descriptor.Descriptor(
  name='ResponseSearchResults',
  full_name='rsctrl.search.ResponseSearchResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='rsctrl.search.ResponseSearchResults.status', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='searches', full_name='rsctrl.search.ResponseSearchResults.searches', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=537,
  serialized_end=641,
)

_SEARCHHIT.fields_by_name['file'].message_type = core_pb2._FILE
_SEARCHHIT_LOCFLAG.containing_type = _SEARCHHIT;
_SEARCHSET.fields_by_name['hits'].message_type = _SEARCHHIT
_RESPONSESEARCHIDS.fields_by_name['status'].message_type = core_pb2._STATUS
_RESPONSESEARCHRESULTS.fields_by_name['status'].message_type = core_pb2._STATUS
_RESPONSESEARCHRESULTS.fields_by_name['searches'].message_type = _SEARCHSET
DESCRIPTOR.message_types_by_name['SearchHit'] = _SEARCHHIT
DESCRIPTOR.message_types_by_name['SearchSet'] = _SEARCHSET
DESCRIPTOR.message_types_by_name['RequestBasicSearch'] = _REQUESTBASICSEARCH
DESCRIPTOR.message_types_by_name['RequestAdvSearch'] = _REQUESTADVSEARCH
DESCRIPTOR.message_types_by_name['ResponseSearchIds'] = _RESPONSESEARCHIDS
DESCRIPTOR.message_types_by_name['RequestCloseSearch'] = _REQUESTCLOSESEARCH
DESCRIPTOR.message_types_by_name['RequestListSearches'] = _REQUESTLISTSEARCHES
DESCRIPTOR.message_types_by_name['RequestSearchResults'] = _REQUESTSEARCHRESULTS
DESCRIPTOR.message_types_by_name['ResponseSearchResults'] = _RESPONSESEARCHRESULTS

class SearchHit(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEARCHHIT
  
  # @@protoc_insertion_point(class_scope:rsctrl.search.SearchHit)

class SearchSet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEARCHSET
  
  # @@protoc_insertion_point(class_scope:rsctrl.search.SearchSet)

class RequestBasicSearch(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTBASICSEARCH
  
  # @@protoc_insertion_point(class_scope:rsctrl.search.RequestBasicSearch)

class RequestAdvSearch(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTADVSEARCH
  
  # @@protoc_insertion_point(class_scope:rsctrl.search.RequestAdvSearch)

class ResponseSearchIds(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSESEARCHIDS
  
  # @@protoc_insertion_point(class_scope:rsctrl.search.ResponseSearchIds)

class RequestCloseSearch(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTCLOSESEARCH
  
  # @@protoc_insertion_point(class_scope:rsctrl.search.RequestCloseSearch)

class RequestListSearches(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTLISTSEARCHES
  
  # @@protoc_insertion_point(class_scope:rsctrl.search.RequestListSearches)

class RequestSearchResults(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTSEARCHRESULTS
  
  # @@protoc_insertion_point(class_scope:rsctrl.search.RequestSearchResults)

class ResponseSearchResults(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSESEARCHRESULTS
  
  # @@protoc_insertion_point(class_scope:rsctrl.search.ResponseSearchResults)

# @@protoc_insertion_point(module_scope)
